### ISSUE TITLE
ToDo Tracker :: v0.1.0

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/FACETS#16]
Tracking Ticket for To Do items for v.0.1.0 release

### Activity Diary
- [x] Add relevant year for current selected date to display above calendar view

#### Rest Periods
- [x] Set "Remind Me" to be enabled by default to avoid this being unintentionally missed
- [x] Develop logic and functionality for Notifications and refine functionality for Alarms
- [x] Remove Key from Rest Summary
- [x] Remove Wind Down and Wind Up logic from Rest Summary
- [x] Update Rest Period list layout
- [x] Update Dashboard view to pull data from new Database structure
- [x] Update Add, Edit and List Activities to reflect new structure

#### Sleep Wake Pattern
- [x] Add coloured arc areas to signify Wind up/down periods
- [x] Colourise Wind Down and Wind Up text to match coloured arc areas
- [x] Develop reminder settings for each period
- Start of Wind Down
- End of Wind Down
- Start of Wind Up
- End of Wind Up

### Others/Miscellaneous
- [x] Condense on-boarding journey (for testing purposes)
- [x] Remove FACETS options from settings (for testing purposes)
