### ISSUE TITLE
[TRACKER] Supervised Testing Summary (Bristol 1)

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/FACETS#73]
#### Tutorial
- [x] Pulse needs to be reinstated to highlight appropriate click area
- [ ] Cancel Tutorial Functionality needs to trigger dialog confirmation
- [ ] Full screen elements need to be changed either to:
    - Blurred Backgrounds (or Semi-Transparent Black)
    - Callout Tooltips with arrows
- [x] Slow down transitions (Menu changes/open) to highlight steps
- [x] Add introduction step to explain

#### Activity Diary
- [ ] Redesign View Activity (#74)
    - [x] Move action buttons from overflow to Toolbar
- [x] Trigger `hasChanged` when save is attempted on `AddActivity`
- [ ] Option to delete additional fields once added
- [ ] Add rests automatically to Heatmap
                                       
#### Rest & Sleep Routine
- [x] Trigger `hasChanged` when `TimePicker` is changed
- [x] Trigger `hasChanged` when save is attempted
- [x] Remove "Reminder Settings" title (Rest Periods)
- [x] Add a "Did you take your rest?" check notification at the end of a rest
    - [x] Controlled with preference
- [x] Add a "How did you sleep?" check notification at the end of wind up
    - [x] Controlled with preference
- [ ] Create & store app based tones to improve suitability vs. built in tones
- [ ] Add dialog to choose snooze time & add snooze ability for notifications
- [ ] Develop snooze functionality

#### Recap Elements
General feedback from the recap sections is that they are lengthy and wordy in places, however, layout and design have been liked. Improvements in visibility are being developed and discussed and will be scoped once agreed.

#### General
- [x] Improve validation
    - [x] Group validation errors to prevent misinterpretation
    - [x] Highlight Validation errors in Red and clear on change

### Bugs
- [ ] Custom notification sound not sounding (forces default)
- [x] Custom Duration chip and time selection issues

### Requests
- [x] Notes Area
- [x] Appointments

#### Roadmap (TBC)
- Google Assistant & Amazon Alexa integration (Activities & Rest Periods)
- Guided Interactive Videos to introduce sections (can be replayed at any time)
- Tailored Recap videos to sit alongside streamlined text content
